name: Build and push Docker images
on:
  workflow_run:
    workflows: ["Build and test"]
    types: [completed]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
        - uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  
        - name: Build and push backend Docker image
          run: |
            docker build -t bobapp-back .
            docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest
          
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:

      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        run: |
          docker build -t bobapp-front .
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest
