name: SonarCloud

on:
  push:
    branches:
      [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  backend-analysis:
    runs-on: ubuntu-latest
    name: Build and analyze

    defaults:
      run:
        working-directory: ./back

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin" # Alternative distribution options are available.

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Pertoldi_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD


  # frontend-analysis:
  #   name: Build and analyze
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [20]

  #   defaults:
  #     run:
  #       working-directory: ./front

  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

  #     - name: Analyze on SonarCloud
  #       uses: SonarSource/sonarcloud-github-action@master
  #       with:
  #         args: >
  #           -Dsonar.projectKey=Pertoldi_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
  #           -Dsonar.organization=pertoldi
  #           -Dsonar.projectBaseDir=front/
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

          