name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  test-back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "maven"
      - name: Install backend dependencies
        run: mvn clean install

      - name: Execute tests
        run: mvn clean test

      - name: Creation of the code coverage report
        run: mvn jacoco:report

      - name: Upload JaCoCo coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: ./back/target/site/jacoco

  test-front:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm i -g @angular/cli@14
      - run: npm run build
      - run: ng test --browsers ChromeHeadless --watch=false --code-coverage

      - name: Upload karma coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: karma-coverage-report
          path: ./front/coverage/bobapp