name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened]

jobs:
  test-back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"
      - name: Install backend dependencies
        run: mvn clean install

      - name: Execute tests
        run: mvn clean test

      - name: Creation of the code coverage report
        run: mvn jacoco:report

      - name: Upload JaCoCo coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: ./back/target/site/jacoco

